version: '3.8'

services:
    db:
       image: mysql:8.0
       ports:
        - '3306:3306'
       restart: always
       environment:
         MYSQL_DATABASE: 'history_web'
         MYSQL_ROOT_PASSWORD: 'Abc123456@'
       volumes: 
         - db-data:/var/lib/mysql
         - ./db/backup/files/:/data_backup/data

    backend_history:
       container_name: nestjs_history
       image: nestjs-api-history:1.0.0
       build:
           context: .
           target: backend
           dockerfile: Dockerfile
       volumes:
         - .:/usr/src/app
         - /usr/src/app/node_modules   
       ports:
         - 5000:5000
       restart: unless-stopped

    migration:
      build:
        context: .
      command:
        [
          "./wait-for-it/wait-for-it.sh",
          "db:5432",
          "--",
          "npm",
          "run",
          "migrate"
        ]
      links:
        - db
      depends_on:
        - db
      env_file: ./.env
      environment:
        - DB_HOST=database_application
    
volumes: 
  db-data: