version: '3.8'

services:
    db:
       image: mysql:8.0
       ports:
        - '3306:3306'
       restart: always
       networks:
        - nesjs-network
       environment:
         MYSQL_DATABASE: 'history_web'
         MYSQL_ROOT_PASSWORD: 'Abc123456@'
       volumes: 
         - db-config:/etc/mysql
         - db-data:/var/lib/mysql
         - ./db/backup/files/:/data_backup/data
    backend_history:
       container_name: nestjs_history
       image: nestjs-api-history:1.0.0
       build:
           context: .
           target: backend
           dockerfile: Dockerfile
       volumes:
         - .:/usr/src/app
         - /usr/src/app/node_modules   
       networks:
         - app-network
       ports:
         - 5000:5000
       restart: unless-stopped
    
networks:
    nesjs-network:

volumes: 
  db-config:
  db-data: